### ISSUE TITLE
pants plugin not compatible with Intellij 15.0.3

### ISSUE THREAD

**Issue by hhaohuang** [pantsbuild/intellij-pants-plugin#100]

**Comment by erikformella** [comment]
I think I am also experiencing this issue.

Pants is no longer listed in the import wizard
![image](https://cloud.githubusercontent.com/assets/463630/12440076/bb673786-beec-11e5-92ac-75f90296b881.png)
![image](https://cloud.githubusercontent.com/assets/463630/12440082/c48632ae-beec-11e5-9020-4c45ff3090c0.png)

**Comment by erikformella** [comment]
after uninstalling the plugin, it no longer shows up when browsing
![image](https://cloud.githubusercontent.com/assets/463630/12440164/8556ecb2-beed-11e5-9763-3563d513abee.png)

**Comment by erikformella** [comment]
version 1.3.10 fixes this for me

**Comment by wisechengyi** [comment]
https://plugins.jetbrains.com/update/index?pr=&updateId=23515
