### ISSUE TITLE
Idea 2016.1 support

### ISSUE THREAD

**Issue by alari** [pantsbuild/intellij-pants-plugin#115]
The latest Idea is not supported: structure never refreshed, pants tab doesn't appear, etc.

**Comment by wisechengyi** [comment]
My guess is that it may not be supported until mid Q2 or later

**Comment by alari** [comment]
any updates or estimates for this?

**Comment by alari** [comment]
or maybe there's any workaround? to update IDEA project structure from command-line?

**Comment by wisechengyi** [comment]
the workaround is to stay on 15

**Comment by backuitist** [comment]
For this particular reason, it'd be great if jetbrain would join this effort:
https://youtrack.jetbrains.com/issue/SCL-10224

**Comment by wisechengyi** [comment]
https://rbcommons.com/s/twitter/r/3780

**Comment by wisechengyi** [comment]
https://plugins.jetbrains.com/plugin/7412 1.4.1
