### ISSUE TITLE
Improve performance by cache results from pants commands that already run

### ISSUE THREAD

**Issue by peiyuwang** [pantsbuild/intellij-pants-plugin#120]
Placeholder so I can place in the code as TODO.

Idea is simple if by caching pants command results (keyed by cmdline) we save time running the same cmd again.

The caveat is if there maybe changes so same command may have different result, so it's safe not to cache anything related to targets, but goals like `options` or `export` without targets should be safe (unless there is pants upgrade during the session, which is super rare, in this case we could have pants version be part of the cache signature)

**Comment by stuhood** [comment]
@peiyuwang : Should definitely not do this. Instead, we should continue to focus on making pants faster.

**Comment by peiyuwang** [comment]
makes sense, engine/graph work would make pants command much faster.

i will comment in code and close this one.
