### ISSUE TITLE
Project name should be folder name when importing from root folder 

### ISSUE THREAD

**Issue by backuitist** [pantsbuild/intellij-pants-plugin#141]
So I'm doing this: https://github.com/pantsbuild/intellij-pants-plugin#importing-multiple-build-filesdirectories and selecting the root folder of my project, say `some-project`. I would expect my project name to be `some-project` instead of `./::`.

**Comment by peiyuwang** [comment]
@backuitist Is your `pants` under `some-project`? IIUC, the project name is determined by the relative path from where `pants` is to the project path. [1]

[1] See [PantsCompileOptionsExecutor.getProjectName](https://github.com/pantsbuild/intellij-pants-plugin/blob/master/src/com/twitter/intellij/pants/service/PantsCompileOptionsExecutor.java#L114-L120)

**Comment by wisechengyi** [comment]
+1 what @peiyuwang said. 
@backuitist if it is easily reproducible, does any of the examples/ or testprojects/ under pants repo have the same issue for you?

**Comment by backuitist** [comment]
I've looked into the project and couldn't find any integration test importing from root folder. There was also no project name assertions.
See https://github.com/pantsbuild/intellij-pants-plugin/pull/143
I'm not sure how to add a test that checks importing from root folder: integration test resources seem a little scattered: there are some in `.cache/pants/examples` and others in `testData/testprojects`... what's the difference? I guess to not mess around with other test resources we would need another project with a pants setup in it and a few modules.. maybe that requires some scripting work as the pants version is a test parameter?

**Comment by backuitist** [comment]
This is broken again, probably due to https://github.com/pantsbuild/intellij-pants-plugin/commit/f3566aba3022844632aa0f0a7ca5ed9cfb8aac4e
As long as there is no test for this it'll keep breaking... and see https://github.com/pantsbuild/intellij-pants-plugin/issues/159 for why there isn't a test.

**Comment by wisechengyi** [comment]
if you are using `idea-plugin` goal, the project name is not determined by the plugin. [this](https://github.com/pantsbuild/pants/commit/769b0adbfffb0badd4070c3d175d537e6d2a749b) addresses this issue, but that means you'd have to upgrade pants to `1.2.0-dev6`

Otherwise the tests you contributed should be still there 7598462669bb20f1913650bbdc0f7faf2272b930

**Comment by wisechengyi** [comment]
although it does make sense to include the `<buildroot>` itself in the project name.

**Comment by backuitist** [comment]
> if you are using idea-plugin

I'm not, this issue is not about that (see the first comment).

> Otherwise the tests you contributed should be still there

Yeah but there are no tests for this: I just said that in my previous comment and it's written in the commit you pointed:
`Given the current state of the testing infrastructure no root import could be tested`.

**Comment by wisechengyi** [comment]
Just to be clear, instead of `.::`, it should be `play2::` or some sort?

![screen shot 2016-08-28 at 11 53 43 pm](https://cloud.githubusercontent.com/assets/596358/18043129/af7c2188-6d7a-11e6-951e-6f3ebb66284b.png)

from https://github.com/ActionIQ/play-pants.git

**Comment by backuitist** [comment]
Hi, thanks for the quick answer!
Yes, when I fixed (pants plugin 1.4.3) it it was `play2` (the `::` are useless IMO).

**Comment by wisechengyi** [comment]
Ah i see, sorry about that. As you said, there was no test hence i didn't even realize it. The instrumentation can be done by setting up another repo during test time, by placing a `dummy` project like <repo>/.cache/dummy, and then import `dummy::` to test against it.

**Comment by wisechengyi** [comment]
https://rbcommons.com/s/twitter/r/4197/. @backuitist if you wanna take a look

**Comment by backuitist** [comment]
That's great! Thanks
