### ISSUE TITLE
Replace RBT by Github PR reviews

### ISSUE THREAD

**Issue by backuitist** [pantsbuild/intellij-pants-plugin#155]
The intellij-pants-plugin uses RBT to carry its reviews instead of Github's for a few reasons:
 1. RBT can squash commits, avoiding the annoying merge commit
 2. RBT is better (arguably) at decent sized reviews
 3. RBT is used by pants (and probably a lot of other projects at twitter), making reviews consistent across pants-related projects.

Now that Github released the squash commit feature (https://github.com/blog/2141-squash-your-commits) 1. is gone.
Secondly, even if RBT was better at decent sized reviews, this project isn't getting as much attention as pants.
Last, it can make sense to have a consistent review process across internal projects but if the intellij-pants-plugin gets contributions from non-twitter developpers, that consistency becomes irrelevant.

Then let's look at the downsides:
 * that's another tool to learn
 * for every PR all the information needs to be duplicated in another form
 * RBT has all sort of quirks: during my last RB ticket it couldn't figure out the diff correctly ending up showing incorrect changes

**Comment by ericzundel** [comment]
Note that we have accepted PRs for stuff we aren't actively working on like jmake, jar-jar.  But intellij-pants-plugin is pretty active with a lot of activity in our rbcommons:  

https://rbcommons.com/s/twitter/r/?sort=-repository%2C-time_added&page=59

The squash commit feature is good, but there are a lot of other things we get with RB that we find github PRs lacking for:

- A template on closing
- A workflow that allows for approvals
- Being able to accurately see diffs between reviews
- A threaded conversation about a topic

We are aware that this workflow is cumbersome and  this is a barrier to accepting outside contributions.  We have a push to try to switch things over to phabricator, but we haven't gotten there yet.

What I always do to make posting to rbcommons is 

1) squash my commit in git to one change
2) rbt post -r <review> --tracking-branch=HEAD~1

This is less than ideal, but the rbcommons keeps a good track of history and I don't miss the individual commits missing.

**Comment by wisechengyi** [comment]
mark as closed. feel free to reopen if there's new information.
