### ISSUE TITLE
Support IntelliJ 2016.2 EAP

### ISSUE THREAD

**Issue by ryan-williams** [pantsbuild/intellij-pants-plugin#162]
At least through IntelliJ, I'm not able to find/install the plugin; I'm on version 162.74.16 fwiw.

**Comment by wisechengyi** [comment]
Right, the version range right now is 145.*, https://plugins.jetbrains.com/plugin/7412
We haven't got the chance to explore 2016.2 EAP yet. At least I am surprised that there's branch bump from 145 to 162 within 2016, so chances are something will break, and we'll have to fix it.

**Comment by wisechengyi** [comment]
1.4.4 and up supports 2016.2
