### ISSUE TITLE
Generalize the plugin to support bazel?

### ISSUE THREAD

**Issue by ittaiz** [pantsbuild/intellij-pants-plugin#169]
Hi,
I hope the issue won't be offensive mentioning bazel and such but I've started working on bazel adoption in my organization and this plugin looks very impressive (well done!).
Seeing as pants and bazel share a lot of common concepts it sounds reasonable to me (without reading the code) that maybe we can generalize the plugin to support both pants and bazel.
Is it of interest to you? I'm of course willing to do most of the work

**Comment by wisechengyi** [comment]
Hi @ittaiz, thanks for bringing up the issue. While I agree with you that pants and bazel share a lot in common, without going into too much detail, there are quite a few differences and very pants specific APIs (developed mostly for the plugin) that this plugin deals with, which makes it really hard, not impossible, to decouple from pants.

I guess the fundamental question is why? Unless your vision is to unify all/major build tool plugins, it may be easier to (fork off this repo if you like and) develop bazel's only plugin.

Just my 2 cents.

**Comment by ittaiz** [comment]
For me the reason was that Bazel, Pants and Buck share a lot of concepts
which strongly affect working with IntelliJ (mainly the fact that you're no
longer integrated by binaries but by source and you need to use the tool
cache).

It's very much possible that although a lot of concepts are shared the
implementation is so different there's no point in this sharing.

I appreciate the offer to use your work, and I'll indeed use it if you
decide this generalization is irrelevant.

Whatever you decide is fine by me

**Comment by fkorotkov** [comment]
@ittaiz FYI bazel team are going to announce IDE soon after 0.3 release. See [this topic](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bazel-discuss/pJMaOJB1Asc/8FALh4W8BAAJ) for details.

To support bazel it will require to get a project info similar to what the plugin gets from `export` goal. See [this doc](https://github.com/pantsbuild/intellij-pants-plugin/blob/master/CONTRIBUTING.md#how-the-plugin-works) for details about how the plugin works with the build system.

**Comment by wisechengyi** [comment]
@ittaiz At this moment it is more reasonable to go separate ways especially with @fkorotkov 's comment. However, if you want to start up a company to unify all build tools, please do let me know ;)

**Comment by ittaiz** [comment]
Fair enough, thanks for your attention
