### ISSUE TITLE
Can't execute some Pants tasks like run because of multiple targets "::" are always specified.

### ISSUE THREAD

**Issue by niw** [pantsbuild/intellij-pants-plugin#181]
### Repro steps

1. Create a directory in the Pants root with next files.

    *BUILD*

        jvm_binary(
          name='test',
          basename='test',
          main='Main',
          dependencies=[
            ':main'
          ]
        )
        scala_library(
          name='main',
          sources=globs('*.scala')
        )

    *Main.scala*

        object Main {
          def main(args: Array[String]) { println("Meow") }
        }

2. Open the created directory in the IntelliJ with Pants plugin.
3. Create a Pants run configuration in the Run/Debug configuration dialog with next settings.

    Pants project: test/test
    Tasks: run

### Expected behavior

Run test:test target and print  "Meow"

### Actual behavior

Prints an error message.

    Executing external task 'run'...
    pants --no-colors run test/::PantsUtil command
    /* snip */
    FAILURE: Multiple targets specified: ...

## Issue

Due to recent change #124 on `PantsTaskManager.java` (https://rbcommons.com/s/twitter/r/3670/diff/6-7#13), the target used by `pants` commands executed by the plugin are always having `::` at the end of project path.

This works many cases for `test` goal, but doesn't work with `run` or any other goals which expects a single target.

I don't know why this change was required but the behavior is definitely regression.

**Comment by wisechengyi** [comment]
Thanks for bringing up the issue. I will make sure to have a test for this use case to prevent regression. For now you might have to go with an earlier version of the plugin. 

Also overall Pants configuration is very much tailored for test, and I think the plan is to make it more generic cases such as being able to handle `run` and other goals.

**Comment by vnu** [comment]
Any updates on this?

**Comment by wisechengyi** [comment]
Fixed at https://github.com/pantsbuild/intellij-pants-plugin/commit/bef84b8f106553696c0a6df7adc2605bb6702dfd pending the next release.

**Comment by wisechengyi** [comment]
But You can always check out the code build A temporary version if needed.

**Comment by wisechengyi** [comment]
@vnu @niw please find the temp build as below. 

To install:
Preferences -> Plugins -> Install plugin from disk -> select the zip

[pants_1.4.4.temp.cf1c477980f5e6cfc32d7393669ff981d90ff03b.zip](https://github.com/pantsbuild/intellij-pants-plugin/files/417281/pants_1.4.4.temp.cf1c477980f5e6cfc32d7393669ff981d90ff03b.zip)

**Comment by wisechengyi** [comment]
https://github.com/pantsbuild/intellij-pants-plugin/releases/tag/release_1.4.5

**Comment by vnu** [comment]
Thanks @wisechengyi 👍

**Comment by xcv58** [comment]
After updating to the 1.4.5. If I hit Run button

It will run:
```bash
pants runPantsUtil command
```

But I can run individual target by appending target path and name to the "Tasks".

I feel wired to do this. One more thing, if I hit Debug button this target, I get:
> Debugging of multiple tasks is not supported!

Is the appending target to `run` correct way to run a target?

**Comment by wisechengyi** [comment]
@xcv58 you would want to remove the existing configuration first. then right click on the test, it will generate a new one with the fix

**Comment by xcv58** [comment]
Thanks @wisechengyi I'm manually configuring like this:

![screenshot 2016-08-22 13 55 57](https://cloud.githubusercontent.com/assets/503123/17871398/30eba276-6870-11e6-85fc-bdac557ee295.png)

It does work. Please tell me if I did anything wrong. Thanks in advance.

But debugging doesn't work.

**Comment by wisechengyi** [comment]
Tasks: `run`
`cim/identify:jar` should be in script parameters. 

the plugin tries to append certain debug options based on `Tasks` https://github.com/pantsbuild/intellij-pants-plugin/blob/79eda0df68f28ec8353749e7dc0f2745da6048dd/src/com/twitter/intellij/pants/service/task/PantsTaskManager.java#L107-L107

**Comment by xcv58** [comment]
I really appreciate your help @wisechengyi ! It works for both `Run` and `Debug`.

For those who have similar issue:
![screenshot 2016-08-22 14 05 06](https://cloud.githubusercontent.com/assets/503123/17871676/79f261d4-6871-11e6-9d9b-2df803e0ae51.png)
