### ISSUE TITLE
Cannot run JUnit test anymore

### ISSUE THREAD

**Issue by backuitist** [pantsbuild/intellij-pants-plugin#201]
I'm using pants 1.1.0 and intellij-pants-plugin 1.4.6. When right clicking on a JUnit test intellij offers 2 options (can't remember what the difference is, and the documentation seems outdated).
They both fail, the first with an error saying that 'Pants supports manifest jar, but it is not found.', the second with no message whatsoever.

**Comment by wisechengyi** [comment]
do you see <buildroot>/dist/export-classpath/manifest.jar after compile succeeded? 
it would be helpful there's a repro against some code.

**Comment by wisechengyi** [comment]
oh also if it was upgraded from 1.4.4 or older, it's better to refresh and nuke the existing run configurations first

**Comment by backuitist** [comment]
Ok, I guess the reason is that I have overriden pants distdir:
```
[DEFAULT]
pants_distdir: .pants.d/dist
```

> it's likely you just need to press a button

that did it thanks!

**Comment by backuitist** [comment]
In fact I created an issue for this: https://github.com/pantsbuild/intellij-pants-plugin/issues/167
So I'll close this one.
