### ISSUE TITLE
Autoscroll from source option for the pants projects view

### ISSUE THREAD

**Issue by efroese** [pantsbuild/intellij-pants-plugin#212]
Sometimes you need to refresh an external pants project in the pants projects view. It'd be useful if there was an "Autoscroll from source" option like the "Project Files Tree" view so the pants window would "snap" to the project that contains the file that's currently focused in the editr view.

**Comment by wisechengyi** [comment]
iiuc https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjCt9CR5PbPAhVMaT4KHQ0tABQQjRwIBw&url=http%3A%2F%2Fwww.biliyu.com%2Farticle%2F42.html&psig=AFQjCNHOiDLB_WFuvW3CiLZtsV4-rLB5og&ust=1477513288858143 should do the trick.

**Comment by wisechengyi** [comment]
Closing ^ should do the trick. Feel free to reopen if it wasn't clear.
