### ISSUE TITLE
The plugin has an inspection that assumes Twitter pants.pex deployment conventions

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/intellij-pants-plugin#22]
plugin-version: 1.0.0
intellij-version: 13.1.4
os/platform: Linux 3.13.0-36-generic x86_64
1. Open a BUILD and see 'Pants library not found' yellow error-stripe in BUILD file editor header.
2. Click 'Fix it' on RHS of stripe.
   Error: 'Couldn't find pants_version in pants.ini'
3. Added the following to pants.ini 
   `
   [DEFAULT]
   pants_version: 0.0.24
   `
4. Click 'Fix it' on RHS of stripe.
   Error: 'Couldn't find a folder with pex files!'

These errors occur in the context of an inspection added by the pants plugin, so I was able to just diable the inspection.

It seems though that this inspection is Twitter-specific.  OSS pants users are in no-way required to run from a pex and `pants_version` is not even a config parameter defined by OSS pants.

Looks like, in particular, this code assumes Twitter pants deployment conventions: https://github.com/pantsbuild/intellij-pants-plugin/blob/master/src/com/twitter/intellij/pants/util/PantsUtil.java#L80

**Comment by wisechengyi** [comment]
probably not applicable now?

**Comment by wisechengyi** [comment]
close due to age.
