### ISSUE TITLE
unable to install with latest IntelliJ

### ISSUE THREAD

**Issue by dmccartney** [pantsbuild/intellij-pants-plugin#223]
I just downloaded the latest IntelliJ Ultimate, it's build 163.7743.
The pants plugin only supports `...162.*` so I can't install the plugin.

**Comment by wisechengyi** [comment]
Ah they just released 2016.3.
 
2016.3 compatibility is in progress but currently blocked by https://youtrack.jetbrains.com/issue/IDEA-164261#u=1479772224213. 

For now please stay on 2016.2.x

**Comment by wisechengyi** [comment]
Ready with #224

**Comment by wisechengyi** [comment]
Release out at https://plugins.jetbrains.com/update/index?pr=androidstudio&updateId=30586
