### ISSUE TITLE
Cannot run specs2 test from within IDEA pants project

### ISSUE THREAD

**Issue by allengeorge** [pantsbuild/intellij-pants-plugin#289]
IDEA has a nifty feature where you can right-click and select "Run as..." for a test. Once I migrated my project to a pants-based project I can't do that anymore.

**Comment by wisechengyi** [comment]
Any example I can try on?

**Comment by wisechengyi** [comment]
@allengeorge what exact error are you seeing? For me IntelliJ was able to recognize and generate a specs2 configuration like below:
![screen shot 2017-04-25 at 2 28 23 pm](https://cloud.githubusercontent.com/assets/596358/25408585/7ac431c8-29c3-11e7-890c-01d5f95b3d45.png)

However Pants may have trouble exporting some classpath causing ClassNotFound

Example from https://github.com/pantsbuild/pants/pull/4516, examples/tests/scala/org/pantsbuild/example/specs2/HelloWorldSpec.scala

**Comment by wisechengyi** [comment]
Just added an example how specs2 should work with Pants https://github.com/pantsbuild/pants/pull/4516

Feel free to open the issue if it does not work for you even after conforming to the example.
