### ISSUE TITLE
2017.2 support

### ISSUE THREAD

**Issue by wisechengyi** [pantsbuild/intellij-pants-plugin#299]
Looks like it will involve quite a few changes.

**Comment by zhiqiangZHAO** [comment]
@wisechengyi is there any plan to resolve this issue in a few days?
Now I have to make decision downgrade my IntelliJ or rest today...

**Comment by wisechengyi** [comment]
Hi @zhiqiangZHAO, it was just out this morning. https://groups.google.com/forum/#!topic/pants-devel/4boulhByhOw
