### ISSUE TITLE
Plugin does not handle multiple java_libraries() in the same BUILD file.

### ISSUE THREAD

**Issue by agenticarus** [pantsbuild/intellij-pants-plugin#30]
Plugin version 1.0.2

Currently it seems as if the plugin picks one 'at random' and sets the module path for all files in the directory. This results in a lot of spurious compilation errors, as the dependencies are different.

**Comment by baroquebobcat** [comment]
There's been a new release. Have you tried this against 1.1?

**Comment by tejal29** [comment]
This has now been fixed in latest versions. Please feel free to re-open if you still see this.
