### ISSUE TITLE
API changes in 2018.1

### ISSUE THREAD

**Issue by sproshev** [pantsbuild/intellij-pants-plugin#327]
`com.jetbrains.python.psi.PyCallExpression#addArgument` was deprecated in 2017 and will be removed in 2018.1.

I found at least one usage [here](https://github.com/pantsbuild/intellij-pants-plugin/blob/master/src/com/twitter/intellij/pants/quickfix/AddPantsTargetDependencyFix.java#L93).

Could you please fix? Sorry for inconvenience.

**Comment by wisechengyi** [comment]
Hi @sproshev thanks for reporting. We are aware of deprecations in a few other places as well, so will fix together for 2018.1

**Comment by wisechengyi** [comment]
Fixed by #335
