### ISSUE TITLE
Non-supported file extensions in resources dependency causes entire project to not load

### ISSUE THREAD

**Issue by mlieberman85** [pantsbuild/intellij-pants-plugin#328]
If I have a pants BUILD file that looks like:

```
scala_library(
    name='lib',
    sources=globs('*.scala'),
    dependencies=[
        ':otherresources',
        'my/other/library'
    ]
)

resources(
    name='otherresources',
    sources=globs('*.something'),
)
```

Imports show up as red and nothing loads correctly in IntelliJ for syntax highlighting, hints, etc. If I remove the "otherresources" target declaration and dependency everything loads fine in IntelliJ. Also if move otherresources into its own folder with its own BUILD file and just do change the original BUILD file to something like:

```
scala_library(
    name='lib',
    sources=globs('*.scala'),
    dependencies=[
        'some/other/directory:otherresources',
        'my/other/library'
    ]
)
```

It works as well. It seems to affect any target that include any files that aren't Scala, Python, and maybe Java.

**Comment by stuhood** [comment]
Which version of pants is this?

**Comment by wisechengyi** [comment]
@mlieberman85 this is due the limitation of IntelliJ that a directory cannot be both source root and resources root. This is equivalent to right clicking on a directory -> `Mark Directory as`, and you can only pick one, so the workaround is like what you mentioned to put them in separate dirs.

**Comment by mlieberman85** [comment]
Thanks. Good to know there's an explanation, helps us sort out how we need to organize our folder/BUILD file structure

Closing the ticket.
