### ISSUE TITLE
A "hack to trick BuildProcessClasspathManager" won't work in 2018.2+

### ISSUE THREAD

**Issue by trespasserw** [pantsbuild/intellij-pants-plugin#333]
The `PantsInitComponentImpl#initComponent` method calls `IdeaPluginDescriptorImpl#setPath` (at [PantsInitComponentImpl.java:50](https://github.com/pantsbuild/intellij-pants-plugin/blob/master/src/com/twitter/intellij/pants/components/impl/PantsInitComponentImpl.java#L50)). In IDEA 2018.2, the call will have no effect (the method is deprecated and scheduled for removal).

If I correctly understood the goal of the hack, you can achieve the same by implementing `BuildProcessParametersProvider` extension. Please let me know if you need any help with that.

**Comment by wisechengyi** [comment]
Thanks for the heads up, @trespasserw! We plan to get to the deprecation issue soon.
