### ISSUE TITLE
Errors are displayed as information in the Messages window

### ISSUE THREAD

**Issue by ericzundel** [pantsbuild/intellij-pants-plugin#34]
I'm using version 1.1.1 distributed through IntelliJ (not a local build)

I see that IntelliJ now delegates to pants for compilation, hooray!

However, errors are now marked as "Information:" in the messages windows.  I've lost the ability to click and navigate to the source code on errors.

Here's a screen shot:

![screen shot 2015-02-19 at 2 34 51 pm](https://cloud.githubusercontent.com/assets/119728/6274449/b6724814-b845-11e4-863e-af7464104262.png)

Here's a snippet of text copied and pasted.

```
Information:pants: Invalidated 2 targets containing 2 payload files.
Information:pants: Compiling a partition containing 13 sources in 2 targets (partition 1 of 1).
Information:pants: 14:34:38 00:06         [compile]
Information:pants: 14:34:38 00:06           [jmake]
Information:pants: Jmake version 1.3.8-9
Information:pants: [31m/Users/zundel/Development/java/.pants.d/gen/protoc/gen-java/com/squareup/protos/geocoding/Service.java:2705: error: package com.squareup.protos.common.location.Location does not exist
Information:pants: private com.squareup.protos.common.location.Location.Coordinates coordinates_;
Information:pants: ^
Information:pants: [m[31m/Users/zundel/Development/java/.pants.d/gen/protoc/gen-java/com/squareup/protos/geocoding/Service.java:2723: error: package com.squareup.protos.common.location.Location does not exist
Information:pants: public com.squareup.protos.common.location.Location.Coordinates getCoordinates() {
Information:pants: [m[31m/Users/zundel/Development/java/.pants.d/gen/protoc/gen-java/com/squareup/protos/geocoding/Service.java:2733: error: package com.squareup.protos.common.location.Location does not exist
Information:pants: public com.squareup.protos.common.location.Location.CoordinatesOrBuilder getCoordinatesOrBuilder() {
Information:pants: [m[31m/Users/zundel/Development/java/.pants.d/gen/protoc/gen-java/com/squareup/protos/geocoding/Service.java:3145: error: package com.squareup.protos.common.location.Location does not exist
```

**Comment by fkorotkov** [comment]
Seems for some reason --no-color is not working and the plugin fails to parse messages. Could you please verify that output of ./pants goal compile <targets> --no-color is not colored in your case.

**Comment by ericzundel** [comment]
That's right. When I run with --no-colors it still shows colors.  I think this is broken in open source pants:


![screen shot 2015-02-19 at 3 02 06 pm](https://cloud.githubusercontent.com/assets/119728/6274829/4a1acc42-b848-11e4-9d14-b670bc145444.png)

@benjyw  Off the cuff, I think the problem is that the option is registered in a way that conflicts with our flag inversion detection logic:

```
/Users/zundel/Src/Pants/src/python/pants/option/global_options.py:  register('--no-colors', action='store_true', help='Do not colorize log messages.')
```

I think this should be

```
register('--colors', action='store_true', default=True, ...)
```

And then we need to invert the logic that reads this flag.  I see others like this.

**Comment by ericzundel** [comment]
I will whip up a quick patch for this since I worked on that part of the code some and it is obviously broken.

**Comment by baroquebobcat** [comment]
I don't understand how `./pants goal compile --no-color` works since compile doesn't have a color flag, and the global flag is `--no-colors`.

**Comment by ericzundel** [comment]
True, but `--no-colors` doesn't work either.

**Comment by baroquebobcat** [comment]
No, I mean, on the command line, specifying `--no-color` results in no colors in our repo, but I don't know where it's registered.

**Comment by ericzundel** [comment]
I am looking at open source pants and I think a change that you don't have broke this flag.

**Comment by ericzundel** [comment]
@baroquebobcat , I just found that --color is a different flag. Its specific to spec_run so you are probably running this on python tests but there is a TODO to use the global one so I'm going to take it away.

**Comment by ericzundel** [comment]
@fkorotkov  I think this investigation has yielded some interesting information.

In summary, the plugin needs to add "--no-colors" at the beginning of the command line if you always want to print with no colors. See:

../intellij-pants-plugin//jps-plugin/com/twitter/intellij/pants/jps/incremental/PantsTargetBuilder.java,  line 105 

--no-color is an option specific to python testing.  It is ignored otherwise.

--no-colors at the end of the command line sometimes fails.  I think clean-all is handled specially and it doesn't work there.

I am going to remove --no-color from the python task in favor of --no-colors.

**Comment by ericzundel** [comment]
You can specify both options for now if you are worried about supporting older versions of pants.   leave --no-color in place at the end of the command line, it will end up just being ignored.  I will add a deprecation message so you will know when it goes away.

**Comment by tejal29** [comment]
Thanks!

**Comment by ericzundel** [comment]
The patch is in to OSS pants at 6453c0f8956a3e10746e811d779c002a42f6748e

The --no-color option deprecation message should display when running scala tests.

**Comment by fkorotkov** [comment]
Thanks a lot for figuring it out!

**Comment by ericzundel** [comment]
Using 1.1.2 EAP from Fedor I  don't see the color escape codes, but errors from my java build are still all marked Information:

![screen shot 2015-02-26 at 9 03 41 am](https://cloud.githubusercontent.com/assets/119728/6393261/88b95ed4-bd96-11e4-9b0d-dd8d3a42a5e5.png)

**Comment by fkorotkov** [comment]
I improved error parsing in 1.3.*. Shouldn't be an issue any more.
