### ISSUE TITLE
Linux Supported?

### ISSUE THREAD

**Issue by svefors** [pantsbuild/intellij-pants-plugin#349]
On my Linux installation (ubutnu 18.04) I can't import any pants project. I see the following output in the idea.log: 
2018-05-24 23:31:27,667 [1725369]   INFO - pants.model.SimpleExportResult - 

Exit code 1 
2018-05-24 23:31:27,668 [1725370]   WARN - nal.AbstractExternalSystemTask - Failed:/home/asdf/projects/pants/pants --no-quiet export --no-colors --export-output-file=/tmp/pants_export_run2509828053969673867.out 
com.twitter.intellij.pants.PantsException: Failed:/home/asdf/projects/pants/pants --no-quiet export --no-colors --export-output-file=/tmp/pants_export_run2509828053969673867.out
	at com.twitter.intellij.pants.model.SimpleExportResult.getExportResult(SimpleExportResult.java:100)
	at com.twitter.intellij.pants.util.PantsUtil.getDefaultJavaSdk(PantsUtil.java:833)
	at com.twitter.intellij.pants.service.project.PantsSystemProjectResolver.lambda$resolveProjectInfoImpl$0(PantsSystemProjectResolver.java:156)
	at java.util.Optional.flatMap(Optional.java:241)

When I run the command that it returns Exit Code 1 directly in bash it works find and I can see the expected file with it;s content.

The reporting server shows me the following:
23:05:28 00:00 [main] 0.397s
See a report at: http://localhost:38155/run/pants_run_2018_05_24_23_05_28_702_3cb56b02257c4332a3df6e207372193c
23:05:28 00:00 [setup] 0.169s
23:05:28 00:00 [parse] 0.000s
Executing tasks in goals: bootstrap -> imports -> unpack-jars -> deferred-sources -> jvm-platform-validate -> gen -> pyprep -> export
23:05:28 00:00 [bootstrap] 0.008s
23:05:28 00:00 [substitute-aliased-targets] 0.000s
23:05:28 00:00 [jar-dependency-management] 0.001s
23:05:29 00:01 [complete] 0.001s
FAILURE

Is the plugin expected to work on Linux or are all/most the developers/contributors of the intellij plugin OS X users?

**Comment by svefors** [comment]
After adding debug level logging in pants.ini it appears to be complaining about missing jdk.

**Comment by baroquebobcat** [comment]
Most of the developers / contributors are on OSX, but I would expect it to work on linux. Do other pants commands work for you, or is it just `export`ing that fails?

**Comment by svefors** [comment]
I just solved it by adding java to the jvm_distribution of pants.ini.

I had installed java using sdkman and all commands worked in regular bash without the jvm_distribution setting. But when the Intellij Plugin invokes the pants there was no knowledge of the sdkman java installation.

**Comment by ngortheone** [comment]
@svefors I have the same problem. I am on OSX

Can you show me what exactly you modified in `pants.ini`?

**Comment by wisechengyi** [comment]
https://github.com/pantsbuild/pants/blob/d064804b3acf89a30fefae3f6900f0414e3e3416/pants.ini#L322-L328 probably.

**Comment by svefors** [comment]
As far as I remember:

[jvm-distributions]paths = {    'linux': [
'/home/svefors/.sdkman/candidates/java/current',    ]}

**Comment by ngortheone** [comment]
I was able to resolve it. 
I had both `jvm_distributions` and `jvm-platform` settings present in pants.ini.

In my case there were some non-UTF8 symbols present in pants.ini and some formatting issues.
Following IDE log stacktrace helped me to resolve it.
