### ISSUE TITLE
intellij builds above 182 not supported

### ISSUE THREAD

**Issue by mrkb80** [pantsbuild/intellij-pants-plugin#360]
The latest version (2018.2) will no longer load the plugin.

I see a few issues (could be more):
1)  plugin.xml says not to: `<idea-version since-build="181.0" until-build="181.*"/>`
2) `PantsSetttings`  uses `StoragePathMacros.PROJECT_CONFIG_DIR` which no longer exists

**Comment by wisechengyi** [comment]
Thanks for the report, @mrkb80 !

1) exists because we know cross major releases, there are usually breakages.
2) Thanks! will look into that.

There's also #333 before 2018.2 can be supported

**Comment by mrkb80** [comment]
Got it.  I can confirm that just bumping the plugin.xml until-build and changing the `PantsSettings` storage will not be enough to support 2018.2 (not sure what else needs to change yet)

**Comment by wisechengyi** [comment]
2018.2 isn't supported yet. Please stay on 2018.1.x for the moment.
