### ISSUE TITLE
running tests with IJ 2018.2 (and plugin 1.10.0) not working

### ISSUE THREAD

**Issue by JasonRosenberg** [pantsbuild/intellij-pants-plugin#369]
Running tests within IJ 2018.2 (with plugin 1.10.0) does not appear to be working (whereas it does with IJ 2018.1.6 (with plugin 1.9.2).

It's running a command like this:

```
pants --no-test-junit-timeouts "--jvm-test-junit-options=-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=56574 -forkSocket56575" test myapp/src/test/java:test --test-junit-test=com.mypackage.myapp.mytest
Running Pants version 2018051601
```

And it shows in the log a big python error trace, with this at the end:
```
Exception message: Unrecognized command line flags on global scope: -f
```

The "-f" flag it's referring to is from the "-forkSocket56575".  The pants test runs fine if I remove this option from the command line:
```
"--jvm-test-junit-options=-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=56574 -forkSocket56575" 
```

If I run the same scenario using IJ 2018.1.6 (with plugin 1.9.2), the command it issues is:
```
pants --no-test-junit-timeouts --jvm-test-junit-options=-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=57149 test myapp/src/test/java:test --test-junit-test=com.myapp.MyTest/Users/myuser/Development/java/pants --no-test-junit-timeouts --jvm-test-junit-options=-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=57149 test myapp/src/test/java:test --test-junit-test=com.myapp.MyTest
```
and that works fine.

**Comment by wisechengyi** [comment]
Hi @JasonRosenberg , could you kindly verify with https://plugins.jetbrains.com/plugin/7412-pants-support/update/48594?

**Comment by JasonRosenberg** [comment]
hi @wisechengyi this works! thanks.....
