### ISSUE TITLE
Can't create a new directory

### ISSUE THREAD

**Issue by JasonRosenberg** [pantsbuild/intellij-pants-plugin#370]
In the file tree pane, there's no option in the menu to create a new directory, when pant plugin is installed.  There are options to create a new class or a new package (and several other options).  But no option to just create a directory.  This is an essential thing to do in our environment, e.g. to create a new pants module, for example.....

**Comment by wisechengyi** [comment]
A limitation so far. Let me know if https://stackoverflow.com/questions/40850396/pants-and-intellij/40856386#40856386 helps.

**Comment by JasonRosenberg** [comment]
hi @wisechengyi I'm not sure I understand?  I just want to be able to create a new directory (anywhere).

Currently, if I right-click on a node in the "Project Files Tree" and navigate to the "new->" sub-menu, I don't see "directory".  I do see these: "Java Class", "File", "Scratch File", "Package", "package-info.java", "HTML File", "Singleton", "Proto File", "SQL Script".....

Whereas in other IntelliJ projects, creating a new directory is an option....
So, instead I have to go to a shell command line and manually add directories, and refresh my IntelliJ project view, and voila, my new directory is visible there.

**Comment by wisechengyi** [comment]
Creating a directory on a non module folder

<img width="932" alt="screen shot 2018-08-06 at 9 11 48 pm" src="https://user-images.githubusercontent.com/596358/43754043-8c9f840e-99bd-11e8-8f29-4e1d2b3fd53f.png">

On a module folder, you can create a package
![screen shot 2018-08-06 at 9 12 38 pm](https://user-images.githubusercontent.com/596358/43754064-aa0e3d1e-99bd-11e8-8eb6-4a74960e4df3.png)

Do you see the same options?

**Comment by JasonRosenberg** [comment]
If I am in a director above any modules, then yes, I see the directory option.  But in our repo, that would be a sum total of 1 directory where I could do that.  Our modules are often nested in an hierarchical way, so if I'm in a module sub-directory, it's very common to need to make a new module in a sub-directory, etc.  Currently, this is not possible.

**Comment by wisechengyi** [comment]
I tried creating a package under a module, which has the same effect as
creating a directory?

**Comment by JasonRosenberg** [comment]
Sure....but it's confusing to not have the option to create a directory......maybe I want to make "scripts" directory, which is not a java "package".....

**Comment by JasonRosenberg** [comment]
And actually, if you try to create a new directory as a "package", IntelliJ then gets confused when you try to make new classes in sub-dirs, it thinks the entire directory path you are trying to create is part of the java class's package name....so it's really confusing....

**Comment by wisechengyi** [comment]
2018 or 2019 seems to have behavior change on this one, so it works now.
