### ISSUE TITLE
Plugin doesn't properly handle tests if both lib and test classes are in the same dir

### ISSUE THREAD

**Issue by JasonRosenberg** [pantsbuild/intellij-pants-plugin#371]
We have many BUILD files in test dirs, that contain both `junit_tests` and `java_library` configs.  The plugin doesn't seem to handle this correctly.  If there's a `java_library` config, then it seems to be cause the plugin to treat all the classes in the dir as library classes, and so it doesn't think it needs to run any tests.  

E.g. if we have a BUILD file like below, non-of the test classes turn green in the IDE, and so don't run unit tests.
```
junit_tests(name='test',
  sources=rglobs('*Test.java'),
  cwd='myapp',
  platform='10',
  dependencies=[
    ':lib',
    ...
    ...
  ],
)

java_library(name='lib',
  sources=rglobs('*.java', exclude=[rglobs('*Test.java')]),
  resources=[
    'myapp:extra-files',
    'myapp:extra-fingerprint-files',
    'myapp/src/test/resources',
  ],
  platform='10',
  dependencies=[
    ...
    ...
  ],
  provides=artifact(
    org='com.mypackage',
    name='myapp-test',
    repo=myrepo,
  ),
)
```

**Comment by wisechengyi** [comment]
This is the limitation of intellij, i.e. one directory could only contain one module, so when pants plugin sees multiple targets in a directory, it makes the compromise to make it a source module over a test module.

It's recommended to separate sources and tests into separate directories.

**Comment by JasonRosenberg** [comment]
ok, I understand.....

**Comment by wisechengyi** [comment]
@johnbcoughlin do you have an example for me to compare?
