### ISSUE TITLE
Unable to run all tests for a directory or project

### ISSUE THREAD

**Issue by mrkb80** [pantsbuild/intellij-pants-plugin#373]
I am unable to execute all tests by any of the following methods:
1) Setup a config to execute all tests in a directory/project/module
2) By right clicking on a folder and clicking Run->Tests in *** 
3) By right clicking on a folder and Click Debug-> Test in ***

When I attempt to run these configs, I see a message stating that no tests are found.

From digging in a bit, it looks like the pants command is correctly building a manifest.jar, handing it off to the junit wrapper, falls back to junit5 (which is different than when I run a single test or test class), and then returns no tests to actually execute.

**Comment by wisechengyi** [comment]
Hi @mrkb80,

Could you clarify which runner are you referring to?
![screen shot 2018-08-06 at 5 03 12 pm](https://user-images.githubusercontent.com/596358/43746690-a759a086-999a-11e8-98aa-d3cb899ba8da.png)

Also are you able to repro the issue with OSS pants?

I imported `examples/tests/java/org/pantsbuild/example/hello/greet/` then run tests against the folder like step 2) and 3), but did not observe the issue.

**Comment by mrkb80** [comment]
@wisechengyi the top command in the menu above (the intellij runner).

What do you mean by the OSS pants?

**Comment by wisechengyi** [comment]
Open source pants repo

**Comment by mrkb80** [comment]
I recreated the exact same issue using the latest version of pants from the github repo:
When I run just a single class or test, no issues, but when I try to run the package:
`0 test classes found in package 'src.test.java.com.example.app.somePackage'`

**Comment by wisechengyi** [comment]
@mrkb80 which project did you import?

**Comment by mrkb80** [comment]
I made my own test project, I can zip it up and drop it here if that is helpful.

**Comment by wisechengyi** [comment]
That'll be great, or push up a branch that I can checkout.

**Comment by mrkb80** [comment]
@wisechengyi I tracked this down to an issue with junit5 in a dependency.  I will attempt to recreate the same scenario in an example project to see if the pants plugin might be able to handle this better, but from what I can tell, this is actually an issue with how intellij determines which junit wrapper to use.

**Comment by mrkb80** [comment]
@wisechengyi you can go ahead and close this.  As I mentioned above, this is an issue with junit4 and junit5 on the classpath at the same time.

**Comment by wisechengyi** [comment]
Thanks for following up, @mrkb80! Just a bit more clarification, do you think that's user code issue or it's a build tool/IDE issue that we need to support?

**Comment by mrkb80** [comment]
It is a user code issue.  You can use the junit vintage engine, which allows you to run older style tests on the new junit platform, or, you can just stick to always using junit4.
