### ISSUE TITLE
Support IntelliJ IDEA 2019.1

### ISSUE THREAD

**Issue by ginomiglio** [pantsbuild/intellij-pants-plugin#392]
I just upgraded from 2018.3, and:

![image](https://user-images.githubusercontent.com/4480856/55255848-d0f63580-5218-11e9-834a-7393c45e834d.png)

**Comment by wisechengyi** [comment]
The new version is in unstable channel now. You can download it and
manually install it.

Will release that one in a few days if there's no issue.

**Comment by danieljanes** [comment]
Thanks @wisechengyi 👍  is there a chance to add PyCharm support as well (#291)?

**Comment by wisechengyi** [comment]
https://github.com/pantsbuild/intellij-pants-plugin/releases/tag/release_1.12.0
