### ISSUE TITLE
Load sources and docs for libraries seems to be broken

### ISSUE THREAD

**Issue by benderpremier** [pantsbuild/intellij-pants-plugin#395]
Since upgrading to intellij `2019.1` and pants plugin `1.12.0` it seems like I can't load the library sources. Even if I configure the plugin with
![image](https://user-images.githubusercontent.com/290994/55499749-a7854180-563e-11e9-8cf9-fbc3bcac4625.png)
IntelliJ only offers me to choose between Decompile and Choose
![image](https://user-images.githubusercontent.com/290994/55500044-5cb7f980-563f-11e9-8b55-f7be4de4499a.png)

**Comment by wisechengyi** [comment]
Did a sanity test on the pants example project and it's able to resolve junit sources.

Depending on what versions of the library you are using, it's possible the sources are not published correctly.

If you can provide more details, e.g. which library is this, that'll be more helpful. If you work at Twitter, feel free to file an internal ticket.

**Comment by benderpremier** [comment]
I don't work at twitter :)

My colleague updated to 2019.1 and can't load the sources either. It doesn't seem to be linked to a particular library. e.g. for `util-core` our dependency looks like this
```
jar_library(name='util-core',
            jars=[
                scala_jar(org='com.twitter', name='util-core', rev=UTIL_REV, intransitive=True),
            ],
            dependencies=[
                '3rdparty/jvm/org/scala-lang:scala-library',
                '3rdparty/jvm/org/scala-lang:scala-reflect',
                '3rdparty/jvm/org/scala-lang/modules:scala-parser-combinators',
                ':util-function',
            ])
```
The `UTIL_REV = '18.3.0`.  I have tried a few other libraries (e.g. `fs2` or `cats-core`) and I can't get the sources either. 

Do I need to set the `apidocs` property while configuring `scala_jar`  ?

**Comment by benderpremier** [comment]
I think I figured it out. We are importing our projects through a `project.sh` script. That script didn't had the flag `--export-libraries-sources` set. Now that the import script looks like:
```
#!/usr/bin/env bash
./pants resolve export \
        --export-libraries-sources \
        src/scala/com/path/to/my/build:: \
```
Everything works as expected. 

I don't know why I use to be able to navigate to the sources with previous version of intelliJ, without that flag set.

But I think we can close this issue :)

**Comment by wisechengyi** [comment]
Thanks for closing the loop!
