### ISSUE TITLE
Better testing of PantsOutputMessage

### ISSUE THREAD

**Issue by fkorotkov** [pantsbuild/intellij-pants-plugin#40]
Right now we have just a few tests for parsing in PantsFilterTest.

First of all we should rename PantsFilterTest to PantsOutputMessageTest and add more tests. Ideally we should write an integration test in case Pants output will be changed. But just reading an output from a file line by line and asserting some output messages should be good enough.

Also we need to investigate which types of messages Pants provides during compilation of both java and scala targets. Is there a difference? Is the format of messages the same for warnings and errors? etc.

**Comment by tejal29** [comment]
@RuShanny Please fell free to mark this closed.
