### ISSUE TITLE
Support IntelliJ IDEA 2019.2

### ISSUE THREAD

**Issue by jorgesg1986** [pantsbuild/intellij-pants-plugin#410]
Currently IntelliJ IDEA 2019.2 is unsupported.
Let me know if you need help.

**Comment by davydkov** [comment]
@jorgesg1986, subscribe to #409

**Comment by captify-eraffenne** [comment]
Any plan to support it soon?

**Comment by wisechengyi** [comment]
Yes, it's WIP

**Comment by wisechengyi** [comment]
Out at https://plugins.jetbrains.com/plugin/7412-pants-support/update/66923
