### ISSUE TITLE
Version IDs in BleedingEdge deployment channels changed recently

### ISSUE THREAD

**Issue by tpasternak** [pantsbuild/intellij-pants-plugin#428]
https://plugins.jetbrains.com/plugin/7412-pants-support/versions

Version `1.13.0.b00a7ed2c9b90db9255ee50d707e11ab1e820aa3` has been deployed twice. The second version ID contains strange apostrophes inside. All newer versions contain these apostrophes as well.

**Comment by wisechengyi** [comment]
They are deployed multiple times due to multiple shards in travis, which isn't a problem really.

Fix at #429
