### ISSUE TITLE
Support for IntelliJ IDEA 2019.3

### ISSUE THREAD

**Issue by ggetv** [pantsbuild/intellij-pants-plugin#450]
IntelliJ IDEA 2019.3 was released, got an error for incompatible Pants plugin 1.13.3. There seems to be a restriction on the version range. Looking forward to a new plugin version that is compatible with IntelliJ IDEA 2019.3. Thanks!

**Comment by wisechengyi** [comment]
we haven't publish a version 2019.3 yet, but in the meantime you can grab the latest one from bleedingedge channel: https://plugins.jetbrains.com/plugin/7412-pants-support/versions

**Comment by wisechengyi** [comment]
we will try to publish one later today

**Comment by ggetv** [comment]
thanks for looking into this so quickly! 👍

**Comment by wisechengyi** [comment]
out at https://plugins.jetbrains.com/plugin/7412-pants-support/update/73614

**Comment by ggetv** [comment]
verified working with the new 1.14 version, thanks again.
