### ISSUE TITLE
Remove resolve.ivy from PantsResolver.

### ISSUE THREAD

**Issue by tejal29** [pantsbuild/intellij-pants-plugin#46]
In rb, https://rbcommons.com/s/twitter/r/2433/ we noted resolve.ivy was no longer needed as the plugin.
We can register products for  export based  task flag --no-libraries.

However due to timing constraints, we shipped this in temporarily https://rbcommons.com/s/twitter/r/2433/

**Comment by ericzundel** [comment]
I think that Garret's recent change to export have changed the way resolution works further.

Reviewed at https://rbcommons.com/s/twitter/r/2905/

**Comment by wisechengyi** [comment]
bascially remove https://github.com/pantsbuild/intellij-pants-plugin/blob/ec84545278463160c71977f789b29a3b3740f723/src/com/twitter/intellij/pants/service/PantsCompileOptionsExecutor.java#L211-L216?

**Comment by benjyw** [comment]
What's the status on this? It would be really nice to get rid of that hack from export.py.

**Comment by wisechengyi** [comment]
5a5aa903537f07005c298e56fbc4e245e560620a
