### ISSUE TITLE
Request for Changelog

### ISSUE THREAD

**Issue by ericzundel** [pantsbuild/intellij-pants-plugin#50]
I like that both Pants and the Plugin are undergoing frequent releases.

I have a request for future changelog entries.  When a new version of the plugin is released, it would be nice to be able to see which version of Pants it was tested with when it was released.  The plugin has been broken for us for at least a few weeks and I'm not sure which version to tell folks to upgrade to.

**Comment by fkorotkov** [comment]
Sorry I was forgetting to update travis.yml to run integration tests agains newer version. But I just updated them to run agains all versions between 0.0.34 and 0.0.44 and it's green: https://travis-ci.org/pantsbuild/intellij-pants-plugin

What exactly is not working?

We are aware of such problem that we can break someone else. As a first step I just introduced beta channel for plugin updates so you can notify us about problems before release. I'm also going to work on a framework for easily testing the plugin in CI in different environments so you'll be able to easily configure a CI job to verify the plugin works in your environment.

<img width="1038" alt="beta" src="https://cloud.githubusercontent.com/assets/989066/9529665/6eed8634-4cb0-11e5-9176-11b6804dcb01.png">

**Comment by ericzundel** [comment]
A developer reported that Tests were not working before we updated to
0.0.44. I'm not sure what version of the plugin he was using. I  just went
through to verify that things are working now and am recommending 1.3.4 or
higher.

**Comment by fkorotkov** [comment]
Yep. Old version of the plugin won't work because this change https://github.com/pantsbuild/pants/commit/ee99c80794e6b77a724bc17194165b971da0a181 changed compiler output paths. Currently the plugin calculates it on it's side. I created https://github.com/pantsbuild/pants/issues/1973 long time ago.

**Comment by wisechengyi** [comment]
closing these since releases are stable more stable now. changes are tracked at the release notes. https://github.com/pantsbuild/intellij-pants-plugin/releases
