### ISSUE TITLE
intellij plugin uses --target-spec-file which was removed

### ISSUE THREAD

**Issue by baroquebobcat** [pantsbuild/intellij-pants-plugin#509]
pants projects fail to load as of 1.27.dev0 with the following message
```
Exception message: Unrecognized command line flags on global scope: --target-spec-file.
```
https://github.com/pantsbuild/pants/commit/ffc4a6099bb15502f2b4e7ea72826e8ce4457752

**Comment by wisechengyi** [comment]
Fixed with https://github.com/pantsbuild/intellij-pants-plugin/commit/99c189b0a34de3e6742751c9053c229ed0fa8bc5

**Comment by wisechengyi** [comment]
https://plugins.jetbrains.com/plugin/7412-pants-support/update/81688
