### ISSUE TITLE
Run tests for a directory

### ISSUE THREAD

**Issue by JasonRosenberg** [pantsbuild/intellij-pants-plugin#54]
In IntelliJ, the junit test runner allows running all tests within a directory or a package (you can do this by right clicking in the file tree view at some point in the directory structure).  However, with the pants plugin, it seems I can only run a test this way if I right click over a particular file.  I am using version 1.3.5 of the plugin (in IntelliJ 14.1.4).

**Comment by fkorotkov** [comment]
With the plugin you can still run tests using JUnit run configurations which allow to do so. Unfortunately Pants itself doesn't provide a way to run tests for a package. Feel free to create such a request so we can use it in the plugin with Pants Run Configurations.

**Comment by JasonRosenberg** [comment]
but in pants you can run tests for a module (or BUILD file, etc.).   And that implies all test classes within that module.  Is there a way to do that?

**Comment by jsirois** [comment]
The semantics would be different than IntelliJ right-click package run tests for non 1-1-1 BUILD files, but I think right-click on a dir running `./pants test that/dir/path:` - note the colon, would be reasonable.  A 2nd context menu entry that used `::` for running all test targets under the dir recursively would probably be useful as well.

**Comment by fkorotkov** [comment]
Sure! For some reason it doesn't appear in the context menu right now(will take a look). But you can manually configure it.

<img width="791" alt="screen shot 2015-09-11 at 10 18 09 am" src="https://cloud.githubusercontent.com/assets/989066/9821330/6eee86dc-586e-11e5-8d8b-f4a3d5609336.png">

**Comment by wisechengyi** [comment]
https://rbcommons.com/s/twitter/r/3206/ should address this issue, but I haven't got around to write the test yet.

**Comment by wisechengyi** [comment]
8d03aff680c4325fb9b26873ca62151279ce3212
