### ISSUE TITLE
Show per test debug output like junit debug output

### ISSUE THREAD

**Issue by JasonRosenberg** [pantsbuild/intellij-pants-plugin#55]
When running tests in IntelliJ using it's default JUnit integration, there are some nice UI features.  Each test shows in a tree structure, and the tests are colored green when they pass and red when the fail, etc.  Also, there's a nice table element showing the time spent per test, etc.

Pants does have a flag --test-junit-per-test-timer  perhaps that could be leveraged?

**Comment by fkorotkov** [comment]
Note that you should be able to run tests using JUnit plugin which has this fancy UI.

**Comment by JasonRosenberg** [comment]
Yes, but to do that, IntelliJ then needs to re-compile everything, which is slower and less incremental than letting pants compile and run the tests.

**Comment by fkorotkov** [comment]
The plugin compiles using Pants!

**Comment by JasonRosenberg** [comment]
Ah, ok, so maybe we should then always use the junit mode for running tests?  Why even have the 'pants test' option?  Does it do anything differently?  Maybe not having the option removes confusion?

**Comment by fkorotkov** [comment]
Unfortunately in our enormous code base we've seen cases when JUnit didn't work. This run configuration producers were added for parity with command line. But Pants Run Configuration is not only about tests. You can configure them to run any pants command and for test and run goals the plugin will automatically modify them to be able to debug tests/running app.

**Comment by JasonRosenberg** [comment]
well, so it looks like running the junit test mode does indeed use pants, but seems to try to compile the entire project, instead of just the dependencies needed for the test at hand.  this alone is a huge reason why that mode is not good enough (as opposed to running just pants test on the selected files/packages)

**Comment by wisechengyi** [comment]
work in progress https://rbcommons.com/s/twitter/r/3493/ will address this issue, at least to the extent of running junit test.

**Comment by wisechengyi** [comment]
332908a47661aeceb458d6b3c631fe9fadb9f7a8
241fe5696fc0f152d20d45e1ad1717a1b38c67a1
