### ISSUE TITLE
Plugin incompatible with Intellij 2020.2

### ISSUE THREAD

**Issue by ykravchuk** [pantsbuild/intellij-pants-plugin#554]
Hello,

Intellij 2020.2 brings many nice features, but Pants Plugin incompatible with 2020.2.
![image](https://user-images.githubusercontent.com/4264046/88973470-cdb50300-d2bf-11ea-8c7c-237d4799c0ff.png)
Could you please update the plugin to support 2020.2?

Thanks,
Yura

**Comment by tpasternak** [comment]
At the moment 2020.2 plugin packages are in Bleeding Edge channel https://plugins.jetbrains.com/plugin/7412-pants-support/versions/bleedingedge

I hope we will publish it to stable channel soon

**Comment by basert** [comment]
Is there any news here?

**Comment by khatkar** [comment]
@basert In the mean time you can manually download the 'bleedingedge' version from [here](https://plugins.jetbrains.com/plugin/7412-pants-support/versions/bleedingedge)
Then in Intellij choose to install plugin from disk
![image](https://user-images.githubusercontent.com/7709729/94028689-0f2ad180-fd8a-11ea-8063-e2f8fd36f755.png)

**Comment by davydkov** [comment]
Bleeding edge version creates module `.-project-root`, that has `/` (filesystem root) as a source folder.
Idea dies trying to analyze it.

Idea 2020.2.1
pants 1.28.0
Mac OS Catalina

**Comment by tpasternak** [comment]
@davydkov thank you for reporting. Do you have any example repo in which I could reproduce it?

**Comment by basert** [comment]
This already started in 1.15.1, see https://pantsbuild.slack.com/archives/C14C1AKHP/p1599745914007000

**Comment by basert** [comment]
I was able to reproduce the issue here: https://github.com/basert/intellij-pants-544
Steps:
- Clone the repo
  - optionally remove the `.idea` folder
- execute `./pants goals` to bootstrap pants
- open intellij, choose `Open or Import`
- select dir
- select these options
![Screenshot from 2020-10-01 14-10-36](https://user-images.githubusercontent.com/1951610/94808475-7cc1a800-03f1-11eb-8477-a92ae9cf2fc2.png)

It will create two projects, the one in the user root will try to index all your files. See the committed `.idea` folder.

**Comment by tpasternak** [comment]
@basert I think it's fixed, could you confirm with the latest bleeding edge? https://plugins.jetbrains.com/plugin/7412-pants-support/versions/bleedingedge

**Comment by basert** [comment]
Gave it a quick try, seems to be fixed! Will report if I encounter broken behavior in the next days.

**Comment by gpereraDX** [comment]
I had issues too, and installed the bleedingedge pointed version and it seems to indexed and set pants multi project properly!

**Comment by basert** [comment]
Used it for a few days now, no issues, performance seems to be even better than before. Can we get a stable release for this?

**Comment by basert** [comment]
@tpasternak Can you make a stable release possible? It's been 3 months now.

**Comment by wisechengyi** [comment]
https://plugins.jetbrains.com/plugin/7412-pants-support/versions/stable/101261
