### ISSUE TITLE
running a test causes full compile of all loaded modules

### ISSUE THREAD

**Issue by JasonRosenberg** [pantsbuild/intellij-pants-plugin#56]
If I right click on a directory to run all tests in the directory, it seems to do a full pants compile on all modules currently loaded into the project, instead of only running pants on the selected module.  Thus we lose the ability to only build the dependencies of the module requested, before running tests.

**Comment by wisechengyi** [comment]
incoming https://rbcommons.com/s/twitter/r/3493/

**Comment by wisechengyi** [comment]
241fe5696fc0f152d20d45e1ad1717a1b38c67a1
332908a47661aeceb458d6b3c631fe9fadb9f7a8
