### ISSUE TITLE
Launching IntelliJ to use plugin from the command line

### ISSUE THREAD

**Issue by ericzundel** [pantsbuild/intellij-pants-plugin#58]
It would be easy for users if there was a shortcut to get their project(s) configured in the plugin.  I'm thinking of an interface where users could easily create a project from the command line.

./pants idea-plugin foo:: bar:: baz::

This is the way 'idea' works today, but we want the features of the plugin.  Maybe the idea-plugin task could write out some kind of config to a file somewhere that the plugin could detect when IntelliJ is launched?

**Comment by wisechengyi** [comment]
What would be a good goal name for this? `plugin`, `idea-plugin`, `init-idea-plugin`?  Open to options of better names. 

cc @stuhood @peiyuwang @baroquebobcat @ericzundel @benjyw @patricklaw

**Comment by wisechengyi** [comment]
`idea-plugin` has been live since 1.4.3 https://github.com/pantsbuild/intellij-pants-plugin/releases
