### ISSUE TITLE
After adding a module, new sub-directories don't get incorporated

### ISSUE THREAD

**Issue by JasonRosenberg** [pantsbuild/intellij-pants-plugin#60]
If I add a module using the pants plugin in IntelliJ, all the java sources are included in the source path for the project.  The files are syntax highlighted, the parent directories have colored icons indicating if they are sources or test packages, and the folder names that contain files have bolded sub module names in square brackets, etc.....

However, if I now want to add a new package sub-directory, containing sources, I can't get IntelliJ to view it as part of the project, and have it be viewed as java sources with syntax highlighting, etc.

**Comment by JasonRosenberg** [comment]
I should add, that some of the directories do let me right click and 'Add package', and then things work correctly.  But if it's at a point a couple levels above one of the leaf directories containing sources, then I don't have that menu choice.....

For example, if I have:  com/company/X/Y/Z/myclass.java

I can right click on Z in the tree, and make a new java package as a sub-directory.
But if I right click on X, then I can only make a new directory (but it doesn't recognize it as a java package), and then any new java sources I put in there aren't viewed as java code, etc.

**Comment by fkorotkov** [comment]
At the moment you need to refresh your project so Pants will add this folder to export goal output. You might create a folder but it might be not in globs of your target.

**Comment by JasonRosenberg** [comment]
Please advise, how do I 'refresh' the project?

**Comment by wisechengyi** [comment]
since 1.4.3, there is Pants Menu at the top, then select "Refresh Pants Project"
