### ISSUE TITLE
Make 'refresh' action more discoverable

### ISSUE THREAD

**Issue by ericzundel** [pantsbuild/intellij-pants-plugin#62]
Using the 'Refresh all ...' action is very useful. Is there a way we could make it more discoverable in the menus?

As inspiration, In the maven plugin, when you right click on items in the project view, there's a menu item 'Maven' that exposes a bunch of actions:

![screen shot 2015-10-20 at 3 49 37 pm](https://cloud.githubusercontent.com/assets/119728/10619192/40b872f8-7742-11e5-9db8-9279f8c0f051.png)

**Comment by wisechengyi** [comment]
currently you can open the pants side panel, then click on "Refresh all pants project". Are you suggesting to add it to somewhere else as well? 

![pants_refresh](https://cloud.githubusercontent.com/assets/596358/11797382/6b938a48-a277-11e5-8391-3da65f29e209.png)

**Comment by wisechengyi** [comment]
https://github.com/pantsbuild/intellij-pants-plugin/pull/88

**Comment by ericzundel** [comment]
I've not seen the pants side panel before. I think this plus #89 should be sufficient for now.
