### ISSUE TITLE
setup-ci-environment.sh should check for all env variables to be set before it runs

### ISSUE THREAD

**Issue by megaserg** [pantsbuild/intellij-pants-plugin#71]
E.g. I didn't have JAVA_HOME set and the script:
https://github.com/pantsbuild/intellij-pants-plugin/blob/master/scripts/setup-ci-environment.sh#L53
created directory .cache/jdk-libs, failed to put JARs in it, then I've set JAVA_HOME, but script wouldn't copy jars since the dir was already created. 

If the script checked for the env variables to be set, that wouldn't be a problem.

**Comment by wisechengyi** [comment]
https://github.com/pantsbuild/intellij-pants-plugin/blob/master/scripts/setup-ci-environment.sh#L16-L19
